services:
  - type: web
    name: it-asset-handover-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        value: "MarwenSuperSecret2025"
      - key: MAIL_SERVER
        value: "smtp.office365.com"
      - key: MAIL_PORT
        value: "587"
      - key: marwen.khalifa@etonhouse.com.sa
        sync: false
      - key: MAIL_PASSWORD
        sync: false
